### ISSUE TITLE
Error: washingmachine at run

### ISSUE THREAD

**Issue by lebacql** [thecodingmachine/washingmachine#2]
$ /root/washingmachine/washingmachine run -v

Warning: Division by zero in /root/washingmachine/src/Clover/CloverFile.php on line 72

Call Stack:
    0.0001     378160   1. {main}() /root/washingmachine/washingmachine:0
    0.0095    1244376   2. Symfony\Component\Console\Application->run() /root/washingmachine/washingmachine:31
    0.0187    1490272   3. Symfony\Component\Console\Application->doRun() /root/washingmachine/vendor/symfony/console/Application.php:120
    0.0189    1490272   4. Symfony\Component\Console\Application->doRunCommand() /root/washingmachine/vendor/symfony/console/Application.php:189
    0.0189    1490272   5. Symfony\Component\Console\Command\Command->run() /root/washingmachine/vendor/symfony/console/Application.php:826
    0.0192    1493168   6. TheCodingMachine\WashingMachine\Commands\RunCommand->execute() /root/washingmachine/vendor/symfony/console/Command/Command.php:262
    0.0200    1533312   7. TheCodingMachine\WashingMachine\Clover\CloverFile->getCoveragePercentage() /root/washingmachine/src/Commands/RunCommand.php:68

Code coverage: NaN%

                                                                   
  [TheCodingMachine\WashingMachine\Gitlab\BuildNotFoundException]  
  Could not find a build for branch 131:master                     
                                                                   

Exception trace:
 () at /root/washingmachine/src/Gitlab/BuildService.php:114
 TheCodingMachine\WashingMachine\Gitlab\BuildService->getLatestBuildFromBranch() at /root/washingmachine/src/Gitlab/BuildService.php:127
 TheCodingMachine\WashingMachine\Gitlab\BuildService->dumpArtifactFromBranch() at /root/washingmachine/src/Commands/RunCommand.php:143
 TheCodingMachine\WashingMachine\Commands\RunCommand->getCloverFileFromBranch() at /root/washingmachine/src/Commands/RunCommand.php:109
 TheCodingMachine\WashingMachine\Commands\RunCommand->execute() at /root/washingmachine/vendor/symfony/console/Command/Command.php:262
 Symfony\Component\Console\Command\Command->run() at /root/washingmachine/vendor/symfony/console/Application.php:826
 Symfony\Component\Console\Application->doRunCommand() at /root/washingmachine/vendor/symfony/console/Application.php:189
 Symfony\Component\Console\Application->doRun() at /root/washingmachine/vendor/symfony/console/Application.php:120
 Symfony\Component\Console\Application->run() at /root/washingmachine/washingmachine:31

                                                                               
  [TheCodingMachine\WashingMachine\Gitlab\BuildNotFoundException]              
  Could not find a build for commit 131:d145c42efa228b14e28e688aeb9bbe38f879d  
  7fd                                                                          
                                                                               

Exception trace:
 () at /root/washingmachine/src/Gitlab/BuildService.php:94
 TheCodingMachine\WashingMachine\Gitlab\BuildService->getLatestBuildFromCommitId() at /root/washingmachine/src/Gitlab/BuildService.php:112
 TheCodingMachine\WashingMachine\Gitlab\BuildService->getLatestBuildFromBranch() at /root/washingmachine/src/Gitlab/BuildService.php:127
 TheCodingMachine\WashingMachine\Gitlab\BuildService->dumpArtifactFromBranch() at /root/washingmachine/src/Commands/RunCommand.php:143
 TheCodingMachine\WashingMachine\Commands\RunCommand->getCloverFileFromBranch() at /root/washingmachine/src/Commands/RunCommand.php:109
 TheCodingMachine\WashingMachine\Commands\RunCommand->execute() at /root/washingmachine/vendor/symfony/console/Command/Command.php:262
 Symfony\Component\Console\Command\Command->run() at /root/washingmachine/vendor/symfony/console/Application.php:826
 Symfony\Component\Console\Application->doRunCommand() at /root/washingmachine/vendor/symfony/console/Application.php:189
 Symfony\Component\Console\Application->doRun() at /root/washingmachine/vendor/symfony/console/Application.php:120
 Symfony\Component\Console\Application->run() at /root/washingmachine/washingmachine:31

run [-c|--clover CLOVER] [-u|--gitlab-url GITLAB-URL] [-t|--gitlab-api-token GITLAB-API-TOKEN] [-p|--gitlab-project-name GITLAB-PROJECT-NAME] [-r|--gitlab-build-ref GITLAB-BUILD-REF]

http://git.thecodingmachine.com/tcm-projects/cyclades/builds/458#down-build-trace

**Comment by moufmouf** [comment]
Fixed
