### ISSUE TITLE
Gitlab variables

### ISSUE THREAD

**Issue by lowtower** [thecodingmachine/washingmachine#6]
Hi,

gitlab variables have been renamed in [`version 9.x`](https://docs.gitlab.com/ce/ci/variables/#9-0-renaming).
So the variable `CI_BUILD_REPO` is not found.
Workaround `.gitlab-ci.yml`:
```yml
variables:
  CI_BUILD_REPO: $CI_REPOSITORY_URL
```

Cheers,
LT.

**Comment by lowtower** [comment]
Hello @moufmouf,

maybe I am just too stupid to get it working :-(.
I have used the workaround above and added an echo to my `/ci/docker_install.sh`.
The result looks something like the following, both for `$CI_REPOSITORY_URL` and `$CI_BUILD_REPO`:
https://gitlab-ci-token:xxxxxxxxxxxxxxxxxxxx@gitlab.com/xxxxxxxxxx/yyyyyyyyyy.git
I guess that's okay.
Also the `$GITLAB_API_TOKEN` looks okay, when echoing.
Nevertheless, I get an error that `$CI_BUILD_REPO` wasn't found.
```
  [RuntimeException]                                                           
  Could not find the Gitlab URL in the "CI_BUILD_REPO" environment variable (  
  usually set by Gitlab CI). Either set this environment variable or pass the  
   URL via the --gitlab-url command line option.
```
So, I added the command-line parameter `gitlab-url` to the `.gitlab-ci.yaml`:
```javascript
  - /root/washingmachine/washingmachine run -v --gitlab-url "http://gitlab.com/xxxxxxxxxx/yyyyyyyyyy.git"
```
Now, I get an html-error:
```html
[Gitlab\Exception\RuntimeException (404)]                                    
  <!DOCTYPE html>                                                              
  <html>                                                                       
  <head>                                                                       
    <meta content="width=device-width, initial-scale=1, maximum-scale=1" name  
  ="viewport">                                                                 
    <title>The page you're looking for could not be found (404)</title>
/* ... */
```
When I point my browser to the url above, everything is fine and I get my projects main page!

Am I too stupid or is there a bug somehwere?

Thanks for Your patience and help!
Cheers,
LT.

**Comment by moufmouf** [comment]
Oh, thanks a lot for the tips. It's true I haven't tested the washingmachine with Gitlab 9 yet. I'm planning to do that (and fix what needs to be fixed) in the coming weeks.

**Comment by lowtower** [comment]
Hello moufmouf,

thanks for your reply and the work on this project.
I keep this open as a reminder, okay? ;-)

Cheers,
LT

**Comment by moufmouf** [comment]
Fixed!
A number of Gitlab variables were renamed while going in Gitlab 9.
Release 1.2.0 supports both Gitlab 8 and 9.

See: https://github.com/thecodingmachine/washingmachine/releases/tag/v1.2.0

**Comment by lowtower** [comment]
Great work!

Thanks a lot!!
